# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Coral Project 
email: Greg.Barber@washpost.com
description: > # this means to ignore newlines until "baseurl:"
  The Coral Project is an open source project to help publishers of all sizes build better communities around their journalism. We’re creating tools that help everyone to feel safe, respected, and heard.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://coralproject.net" # the base hostname & protocol for your site
twitter_username: coralproject
github_username:  coralproject

# Build settings
markdown: kramdown
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']

# Collection settings
collections:
  products:
    output: true
  users:
    output: true

# Meta settings
name:           "The Coral Project"
logo:           /images/logo.png
locale:         en_us
author:
  facebook:     coralproject
  twitter:      coralproject
facebook:
  app_id:       301497520213821
twitter:
  username:     coralproject

# Redirects
custom_redirects:
  - from: ^/change-of-focus$
    to: http://blog.coralproject.net/change-of-focus/
    type: permanent
